# Generated by Django 3.1.1 on 2020-09-20 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Титул объекта')),
                ('square', models.FloatField(default=38, verbose_name='Квадратура объекта')),
                ('roomnum', models.IntegerField(default=1, verbose_name='Количество Комнот')),
                ('price', models.IntegerField(default=10000, verbose_name='Цена')),
                ('aparroom', models.IntegerField(default=5, verbose_name='Этажность дома')),
                ('gps', models.CharField(max_length=100, verbose_name='Адрес для Риэлтора')),
                ('opis', models.TextField(db_index=True, default='Отсутствует', max_length=500, verbose_name='Описания объекта')),
                ('number', models.CharField(default='+77776907855', max_length=100, verbose_name='Номер Риэлтора')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('typeOf', models.CharField(default='apartament', max_length=13)),
                ('typ', models.CharField(choices=[('Покупка', 'Покупка'), ('Аренда', 'Аренда')], default='Покупка', max_length=20, verbose_name='Категория для объекта')),
                ('cate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grkm.add', verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Imah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(db_index=True, upload_to='apartmentsimg', verbose_name='Изоброжения объекта')),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='apartmentslist.apartments')),
            ],
        ),
    ]
