# Generated by Django 3.1.1 on 2020-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='kolrroom',
            field=models.IntegerField(default=5, verbose_name='Этажность дома'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='aparroom',
            field=models.IntegerField(default=5, verbose_name='На каком этаже дома'),
        ),
    ]
