# Generated by Django 3.1.1 on 2020-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0002_auto_20200920_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='rename',
            field=models.CharField(blank=True, default='Кира', max_length=10, verbose_name='Имя Риэлтора'),
        ),
    ]
