# Generated by Django 3.1.1 on 2020-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0003_apartments_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='pledge',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=25, verbose_name='Залог'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='typwall',
            field=models.CharField(choices=[('Битон', 'Битон'), ('Кирпич', 'Кирпич'), ('Саман', 'Саман')], default='Битон', max_length=25, verbose_name='Материал стен'),
        ),
    ]
