# Generated by Django 3.1.1 on 2020-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0004_auto_20200920_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='ye',
            field=models.IntegerField(default=1970, verbose_name='Год постройки объекта'),
        ),
    ]
