# Generated by Django 3.1.1 on 2020-09-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0005_apartments_ye'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='height',
            field=models.IntegerField(default=3, verbose_name='Высота потолков'),
        ),
    ]
