# Generated by Django 3.1.5 on 2021-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0006_apartments_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='roomnum',
            new_name='roomnumber',
        ),
        migrations.AlterField(
            model_name='apartments',
            name='height',
            field=models.FloatField(default=3, verbose_name='Высота потолков'),
        ),
    ]
