# Generated by Django 3.1.5 on 2021-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentslist', '0007_auto_20210114_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='residential',
            field=models.IntegerField(default=50, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='square',
            field=models.IntegerField(default=7, verbose_name='Общая площадь'),
        ),
    ]
