# Generated by Django 3.1.5 on 2021-01-20 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartmentslist', '0008_auto_20210114_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='rename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
