# Generated by Django 3.1.1 on 2020-09-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(default=None, max_length=86, unique=True, verbose_name='Улица')),
            ],
        ),
    ]
