# Generated by Django 3.1.5 on 2021-01-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(db_index=True, upload_to='get_name', verbose_name='Изоброжения объекта')),
            ],
        ),
    ]
