# Generated by Django 3.1.1 on 2020-09-20 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Титул объекта')),
                ('square', models.IntegerField(default=7, verbose_name='Общая площадь')),
                ('residential', models.IntegerField(default=50, verbose_name='Жилая площадь')),
                ('height', models.IntegerField(default=3, verbose_name='Высота потолков')),
                ('roomnum', models.IntegerField(default=1, verbose_name='Количество этажей')),
                ('building', models.CharField(default='Кирпич', max_length=35, verbose_name='Тип строения')),
                ('ye', models.IntegerField(default=1970, verbose_name='Год постройки объекта')),
                ('adrr', models.CharField(max_length=100, verbose_name='Точный Адрес для риэлтора')),
                ('opis', models.TextField(db_index=True, default='Отсутствует', max_length=50000, verbose_name='Описания')),
                ('price', models.IntegerField(default=3800000, verbose_name='Цена в Tг')),
                ('phonnum', models.CharField(default='+77776907855', max_length=15, verbose_name='Номер Риэлтора')),
                ('rename', models.CharField(blank=True, default='Кира', max_length=10, verbose_name='Имя Риэлтора')),
                ('typeOf', models.CharField(default='house', max_length=8)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('typ', models.CharField(choices=[('Покупка', 'Покупка'), ('Аренда', 'Аренда')], default='Покупка', max_length=20, verbose_name='Категория для объекта')),
                ('cate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grkm.add', verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Imah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(db_index=True, default='/static/houseimg/defa.jpg', upload_to='houseimg', verbose_name='Изоброжения объекта')),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='houselist.house')),
            ],
        ),
    ]
