# Generated by Django 3.1.1 on 2020-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='pledge',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=25, verbose_name='Залог'),
        ),
        migrations.AddField(
            model_name='house',
            name='roomnumber',
            field=models.IntegerField(default=1, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='house',
            name='typwall',
            field=models.CharField(choices=[('Битон', 'Битон'), ('Кирпич', 'Кирпич'), ('Саман', 'Саман')], default='Битон', max_length=25, verbose_name='Материал стен'),
        ),
    ]
