# Generated by Django 3.1.1 on 2020-09-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houselist', '0002_auto_20200920_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='building',
        ),
    ]
