# Generated by Django 3.1.5 on 2021-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselist', '0003_remove_house_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='height',
            field=models.FloatField(default=3, verbose_name='Высота потолков'),
        ),
    ]
