# Generated by Django 3.1.5 on 2021-01-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houselist', '0005_auto_20210119_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rename',
            field=models.CharField(blank=True, default='Кира', max_length=10, verbose_name='Имя Риэлтора'),
        ),
    ]
