# Generated by Django 3.1.5 on 2021-01-19 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houselist', '0006_auto_20210119_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rename',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
